spring:
  application:
    name: hackerthon
  datasource:
    url: jdbc:mysql://localhost:3306/hackerthon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  mail:
    host: smtp.naver.com
    port: 465
    username: op9563_@naver.com
    password: RCFRM75E9KFN
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com
  servlet:
    multipart:
      enabled: true
  session:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
  security:
    oauth2:
          client:
            registration:
              naver:
                client-id: fMWRSwGU3cwCnlHqMzpI
                client-secret: slMWw_rE9H
                redirect-uri: '{baseUrl}/login/oauth2/code/naver'
                authorization-grant-type: authorization_code
                scope: name,email
                client-name: Naver
              google:
                client-id: 600258935760-up8hj2jlsok0suup89gn8r3909aqirrq.apps.googleusercontent.com
                client-secret: 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
                redirect-uri: '{baseUrl}/login/oauth2/code/google'
                scope: profile,email
              kakao:
                client-id: 52a2b1a4cb282e8fca1645dd9e552a8f
                client-secret: GoLt4n0N9AS6hLVWfeeoxD0lACWGeB4Y
                client-authentication-method: client_secret_post
                redirect-uri: 'http://localhost:8080/login/oauth2/code/kakao'
                authorization-grant-type: authorization_code
                scope: profile_nickname,account_email
            provider:
              naver:
                authorization-uri: https://nid.naver.com/oauth2.0/authorize
                token-uri: https://nid.naver.com/oauth2.0/token
                user-info-uri: https://openapi.naver.com/v1/nid/me
                user-name-attribute: response
              kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize
                token-uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user-name-attribute: id

jwt:
  secret: MySuperSecretKeyForJwtSigning123!@#!

file:
  upload-dir: uploads

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

